name       : log4cpp
version    : 1.1.3
release    : 2
source     :
    - https://downloads.sourceforge.net/log4cpp/log4cpp-1.1.3.tar.gz : 2cbbea55a5d6895c9f0116a9a9ce3afb86df383cd05c9d6c1a4238e5e5c8f51d
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A library of C++ classes for flexible logging to files, syslog, IDSA and other destinations
description: |
    A library of C++ classes for flexible logging to files, syslog, IDSA and other destinations.
patterns   :
    - devel :
        - /usr/bin/log4cpp-config
setup      : |
    %patch -p1 < $pkgfiles/stime.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
